// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AppointmentsController from "./appointments_controller"
application.register("appointments", AppointmentsController)

import PatientsController from "./patients_controller"
application.register("patients", PatientsController)
